[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."scheduled-fetch-bg"]
  schedule = "0 20 * * *"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
